language: php
php:
  - "7.2"

addons:
  chrome: stable

install:
  - composer install --prefer-dist

script:
  - cd vendor/symfony/panther/chromedriver-bin && ./update.sh && cd ../../../..
  - composer ci

cache:
  directories:
    - $HOME/.composer/cache/files
