<?php declare(strict_types=1);

namespace webignition\BasilCompilableSourceFactory;

class VariableNames
{
    const PANTHER_CLIENT = 'CLIENT';
    const ENVIRONMENT_VARIABLE_ARRAY = 'ENV';
    const DOM_CRAWLER_NAVIGATOR = 'DOM_CRAWLER_NAVIGATOR';
    const PHPUNIT_TEST_CASE = 'PHPUNIT_TEST_CASE';
    const WEBDRIVER_ELEMENT_INSPECTOR = 'WEBDRIVER_ELEMENT_INSPECTOR';
    const WEBDRIVER_ELEMENT_MUTATOR = 'WEBDRIVER_ELEMENT_MUTATOR';
    const PANTHER_CRAWLER = 'CRAWLER';

    const EXPECTED_VALUE = 'EXPECTED_VALUE';
    const EXAMINED_VALUE = 'EXAMINED_VALUE';
}
