name: Static Analysis

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  phpstan:
    name: PHPStan - PHP ${{ matrix.php-versions }} ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4', '8']
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Download dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-version }}

      - name: PHPStan
        run: composer static-analysis
